services:
  lottery-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_TYPE: "server"
      JAR_ARGS: ""
    ports:
      - "8080:8080"  # Ajusta el puerto según tu server

  lottery-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_TYPE: "client"
      JAR_ARGS: "localhost 3030 client1"

  lottery-seller:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_TYPE: "seller"
      JAR_ARGS: ""

  lottery-dns:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_TYPE: "dns"
      JAR_ARGS: "3030"
    ports:
      - "3030:3030"  # Ajusta si usas DNS real o solo simulado
